[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "vOgVB1tt9ak83ZKqbJmF3iN8_t4NCS-QiZG6NDNHtRGrQIJMkq_dLrgxCGZgLGD0go-BI7RaqVYOdxJroyc5_g"
[auth.auth0]
domain = "dev-eupyxj5g7o5jiyli.us.auth0.com" 
client_id = "sGH5eeWe1vRFOQCBQvheFCKlPX6MX2at"  
client_secret = "s2lveJTS6ffFusk-kMM6YJ25a-nalBx3Lk9e3INcyeJAXUacZnBZJut5ebo3RRNW"
server_metadata_url = "https://dev-eupyxj5g7o5jiyli.us.auth0.com/.well-known/openid-configuration" 
callback_url = "http://localhost:8501/oauth2callback"  # Update for production
logout_url = "http://localhost:8501"  # Update for production
